### ISSUE TITLE
Password Generator

### ISSUE THREAD

**Issue by Tech097353729** [Tech097353729/python-scripts#1]
Password Generator

This script is all about generating passwords. Thinking of new passwords can be annoying, as many websites also require special characters. This generator includes special characters, numbers, upper and lower case in generated passwords.

Generates passwords, random ones. Stores generated passwords in a text file.

**Comment by flow6979** [comment]
hey @Tech097353729, I want to contribute to this issue. can you please assign this to me?

**Comment by vikash485** [comment]
Hello @Tech097353729 , can I contribute to this issue?
